latchset/mod_auth_mellon

- auth_mellon_cache.c
Originally reported at:
https://github.com/Uninett/mod_auth_mellon/pull/213
CC @oss-aimoto
> Fix: size not written to error_log

- auth_mellon_util.c
This PR resurrects https://github.com/Uninett/mod_auth_mellon/pull/220 and fixes CVE-2019-13038
There are also unit tests for `am_validate_redirect_url` added.
The last patch I'm not sure about. It is based on Olav's suggestion in https://github.com/Uninett/mod_auth_mellon/pull/220#pullrequestreview-292190490 and equally on the hardening that was done in mod_auth_openidc, but OTOH it is a change in behaviour and might bite some users. So I'd appreciate opinions.
> Cve 2019 13038

- README.md
- auth_mellon.h
- auth_mellon_config.c
- auth_mellon_cookie.c
- auth_mellon_diagnostics.c
Starting in Chrome 80 in February 2020, cookies without the SameSite attribute set will default to SameSite=Lax. This seems to break mod_auth_mellon when using an external IdP (e.g., Okta) because the mellon-cookie is not sent with the cross-origin POST request from the IdP.
The fix is to set SameSite=None and MellonSecureCookie On. This allows the cookie to be unconditionally sent in cross-origin requests.  Mellon doesn't currently support a value of "None" for SameSite. This change implements this support.
I think long-term it would also be worth considering why Mellon needs that mellon-cookie to come back. It's initially just set to a test value of mellon-cookie=cookietest. Based on the log messages (below), it seems that Mellon assumes the user's browser doesn't support cookies if it …
> Add "None" option for SameSite cookie

- README.md
- auth_mellon.h
- auth_mellon_cookie.c
SameSite=None is not always work better.
https://www.chromium.org/updates/same-site/incompatible-clients
These browsers reject cookie if SameSite=None set.
* chrome 51-66
* android UCBrowser 12.13.2 before
These browsers set SameSite=strick cookie if SameSite=None set.
* MacOS 10.14
* iOS12
> Avoid always set same site

- README.md
- auth_mellon.h
- auth_mellon_config.c
- auth_mellon_httpclient.c
By default, curl will add the "Expect" Header and will wait for 1 sec before sending the body of the message during the HTTP-Artifact binding if the IDP server do not response to the Expect-100Continue.
If the IDP called by the mellon-curl/HTTP-Artifact is an Apache server, the Apache do not support the Expect Header and the Expect Header will be ignored. So the curl will wait for 1 sec (for nothing) before sending the body.
So, to improve performance with the HTTP-Artifact binding, let's have an option to unset the Expect Header of the curl (MellonDisabledCurlExpectLogic Off/On). (for those where the IDP is in front of an Apache server)
> Disabling the Expect Logic saves an additional network round-trip and is thus
> a good idea when the request isn't extremely large and the probability …
> Add option to control whether or not to send the Expect Header

- auth_mellon.h
- auth_mellon_cache.c
- auth_mellon_diagnostics.c
- auth_mellon_handler.c
- auth_mellon_session.c
This is a vulnerability that we found.
It is possible to create several valid mellon session cookies using the same SAML reponse.
The solution is to validate if the assertion ID was already been used before creating a new session.
Ref: https://blog.netspi.com/attacking-sso-common-saml-vulnerabilities-ways-find/, "Messsage Replay"
> Cache SAML Response replay message on new sessions

- README.md
- auth_mellon_handler.c
This PR is for the release of the cache after deleting the session on invalidate endpoint.
Also add information on the readme.md for the mandatory ReturnTo parameter for then /invalidate endpoint.
It seems this correction has been lost on the last PR, so there is the corrections.
> Invalidate endpoint not releasing cache

- README.md
- auth_mellon.h
- auth_mellon_cookie.c
- auth_mellon_handler.c
If the SameSite cookie attribute is to be set because
MellonCookieSameSite is configured and MELLON_DISABLE_SAMESITE not set
for this particular request set it to None for the test cookie.
This ensures that the test cookie with the static test content does not
get lost in the HTTP-POST binding request issued by the autosubmit form
returned by the IDP.
Addresses #20
* auth_mellon.h: Add AM_FORCE_SAMESITE_NONE_NOTE
* auth_mellon_handler.c (am_send_login_authn_request): Set request note
to set SameSite to None if appropriate.
* auth_mellon_cookie.c (am_cookie_params): Set SameSite to None if
requested via request note.
> Set SameSite to None on test cookie

- README.md
Both MellonSessionDump and MellonSamlResponseDump are listed again
later in the file with a bit more documentation.
> Remove duplicate entries from example configuration

- auth_mellon_util.c
there is a bug in the bit logic of the authorization code handling MellonCond directives. Example: you have two users, that can both authenticate successfully with IdP:
sunny
sunny1977
Now you want to restrict access to /beach by doing something like this:
<Location /beach>
AuthType Mellon
MellonEnable auth
MellonUser "uid"
MellonCond uid sunny1977 [NC]
...
</Location>
So only _sunny1977_ should be able to access /beach, but in fact also _sunny_ can access it, because this _if_ condition is true, even the SUB (substring match) option is not set in the configuration. Setting NC is sufficient to provoke this behavior.
} else if (ce->flags & (AM_COND_FLAG_SUB|AM_COND_FLAG_NC)) {
match = (ap_strcasestr(ce->str, value) != NULL);
Using the NC option automatically activates the code path for …
> two bit-logic bugs in authorization code (MellonCond)

- auth_mellon_util.c
Given a configuration of:
```
MellonCond john [SUB]
```
Previously, attribute value "ohn" would match this but "johndoe" not. According to the documentation and I believe common sense, it should be that the configuration above matches any attribute value that contains "john".
> The configured string should be substring of attribute value

- auth_mellon_config.c
Previously the error message would only say lax or strict is allowed.
This is a minor issue because the message would only have been printed
when the admin did a typo in the first place.
Spotted by Kyle Walker.
> Improve error msg when MellonCookieSameSite has an invalid value

- README.md
- auth_mellon.h
- auth_mellon_cache.c
- auth_mellon_config.c
- auth_mellon_diagnostics.c
- auth_mellon_handler.c
The Idle Session Timeout (Inactivity) represents the amount of time a user can be inactive before the user's session times out in seconds.
The Idle Timeout is working with the session length(lifetime) to managed the amount of time the user session cookie­ expired.
This parameter is disabled by default to maintain backward compatibility.
> Add the session idle timeout fonctionnality

- Makefile.in
- configure.ac
`mod_auth_mellon` doesn't build on the distro I use without some fixes.
> fix build for libxml and xmlsec

- auth_mellon_cookie.c
Fixing the issue where the cookie test SameSite was set to None **only** if the `MellonCookieSameSite `was set to something other than default instead of **regardless** of the value (as said in main page)
Addresses #20 and likely #47
> Adjusting the setting of SameSite property for CookieTest

- mellon_create_metadata.sh
ran into the same Issue as #48.
This PR sets `AuthnRequestsSigned="true"` in `mellon_create_metadata.sh`.
> set AuthnRequestSigned true

- auth_mellon_handler.c
When mod_auth_mellon sends logout request to the idP, it gets response back through HTTP GET request. That works fine, However, some idP implementations send the logout response through POST request. Logout response via POST is not understood by mod_auth_mellon and leads to 404 page. The mod_auth_mellon assumes that POST method in logout endpoint is always SOAP logout request. The suggested fix adds a check and POST handler for logout responses.
I also did re-tab in mellon_auth_handler.c source file since some portions of the file mixed tab and space based indentations.
> Logout endpoint should handle idP POST response

- mellon_create_metadata.sh
OpenSSL 3 does not allow randfile to not be a regular file, so using
/dev/urandom as a seed require you to write the data to a seperate
file, and use that.
Fixes #105
> mellon_create_metadata.sh: Fix compatibility with OpenSSL 3

- mellon_create_metadata.sh
Add our certificate as being eligible for encryption as well as signing (to make idPs that require encryption happy)
> Add encryption certificate to generated metadata

- README.md
- auth_mellon.h
- auth_mellon_config.c
- auth_mellon_diagnostics.c
- auth_mellon_handler.c
- configure.ac
- doc/user_guide/mellon_user_guide.adoc
Remove code pertaining to Lasso < 2.4. Given that this was released 2014 it seems safe to drop this now.
Having many ifdefs makes the code less maintainable and also keeps code that is in practice untested around, because the developers never compile the code with ancient lasso versions. Confusing bugs arise because some configuration options only work with some of the code and not the other.
This removes all code not satisfying the presence of:
- lasso_server_new_from_buffers,
- lasso_server_load_metadata,
- lasso_profile_set_signature_verify_hint
It also removes the configuration option MellonIdPPublicKeyFile which would only actually do something if Mellon was compiled with a pre-2.4 lasso, otherwise would just be ignored.
> Remove compatibility with lasso before 2.4

- auth_mellon_compat.h
Today, mod_auth_mellon is comparing the wrong IP address against the IP sent to us by the IdP.  This results in MellonSubjectConfirmationDataAddressCheck failing in a scenario where you are using mod_rpaf or mod_remoteip to update the clients IP address.  This is a common scenario when Apache is behind a load balancer.
In order to fix this, we need to use the useragent_ip variable, instead of connection->client_ip.
The Apache module development guide also recommends this:
https://httpd.apache.org/docs/trunk/developer/modguide.html
> Fix compatibility with mod_rpaf/mod_remoteip + follow Apache Module Dev Guide

- README.md
- auth_mellon_handler.c
- auth_mellon_util.c
- doc/user_guide/mellon_user_guide.adoc
IDP Initiate POST SLO Implementation
> IDP Initiate POST SLO Implementation

- auth_mellon_handler.c
Since our minimum version is 2.4, this is essentially dead code. It was missed in the earlier cleanups (#129) because other compatibility code used ifdefs instead of this construct.
> Remove Lasso < 2.3 compatibility code.

- mellon_create_metadata.sh
Please accept hyphen of the hosts in the OUTFILE's file name.
According to RFC953, the use of hyphens in host names is permitted.
> accept hyphen in host names.
